INFERENCE_DATASET_PATH = "./data/house-prices-advanced-regression-techniques/test.csv"

DROP_COLUMNS = [
    "GarageCond",
    "EnclosedPorch",
    "Condition1",
    "Utilities",
    "GarageCars",
    "BsmtFinSF1",
    "BsmtCond",
    "ExterCond",
    "Condition2",
    "GarageType",
    "Heating",
    "BsmtFinType2",
    "PavedDrive",
    "PoolArea",
    "BsmtFinType1",
    "BsmtFinSF2",
    "HeatingQC",
    "ScreenPorch",
    "CentralAir",
    "3SsnPorch",
    "MiscVal",
    "SaleCondition",
    "BsmtUnfSF",
    "GarageQual",
    "BldgType",
    "LotShape",
    "LandContour",
    "OverallQual",
    "RoofMatl",
    "Electrical",
    "LandSlope",
    "BsmtHalfBath",
    "LowQualFinSF",
    "SaleType",
    "HouseStyle",
    "Exterior2nd",
    "Street",
    "Neighborhood",
    "YearBuilt",
    "KitchenAbvGr",
    "Functional",
]

MODEL_PATH = "../training/model.pkl"
